use std::fmt::Write;
use std::ops::Index;
use std::path::is_separator;

use smallvec::SmallVec;

use crate::pattern::{Ast, is_escape_char};

pub type StateId = u16;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TransitionRule {
    // Epsilon classes
    Epsilon(StateId),
    /// Epsilon edges generated by * or **. Why? When * or ** are part of the
    /// parse, they tag the automaton as being a non-literal match, *even if
    /// the rule matched no characters*. This guarantees that the pattern '.*'
    /// never matches the virtual directory '.'.
    WildEpsilon(StateId),
    // Character classes
    Char(char, StateId),
    Sep(StateId),
    /// Matches anything except for Sep (used by ?, *)
    Wildcard(StateId),
    /// Matches anything including Sep (used by **)
    Any(StateId),
}

impl TransitionRule {
    pub fn is_literal(&self) -> bool {
        match self {
            Self::WildEpsilon(_)
            | Self::Wildcard(_)
            | Self::Any(_) => false,
            Self::Epsilon(_)
            | Self::Sep(_)
            | Self::Char(_, _) => true,
        }
    }

    pub fn is_epsilon(&self) -> bool {
        matches!(self, Self::Epsilon(_) | Self::WildEpsilon(_))
    }

    pub fn next(&self) -> StateId {
        match self {
            Self::Epsilon(target)
            | Self::WildEpsilon(target)
            | Self::Char(_, target)
            | Self::Sep(target)
            | Self::Wildcard(target)
            | Self::Any(target) => *target,
        }
    }

    pub fn matches(&self, token: char) -> bool {
        match self {
            Self::Char(c, _) => token == *c,
            Self::Sep(_) => is_separator(token),
            Self::Wildcard(_) => !is_separator(token),
            Self::Any(_) => true,
            // Epsilon transitions never consume input
            Self::Epsilon(_) | TransitionRule::WildEpsilon(_) => false,
        }
    }
}

pub type Transition = TransitionRule;

#[derive(Debug, Default)]
pub struct State {
    pub transitions: SmallVec<[Transition; 1]>,
    pub is_epsilon_frontier: bool,
}

impl State {
    // Debug code
    pub fn show_accepts(&self) -> String {
        let mut out = String::new();
        for t in self.transitions.iter() {
            let _ = match t {
                TransitionRule::Epsilon(_)
                | TransitionRule::WildEpsilon(_) => write!(out, "ε"),
                &TransitionRule::Char(c, _) if is_escape_char(c) => write!(out, "\\{c}"),
                TransitionRule::Char(c, _) => write!(out, "{c}"),
                TransitionRule::Sep(_) => write!(out, "{}", std::path::MAIN_SEPARATOR),
                TransitionRule::Wildcard(_) => write!(out, "?"),
                TransitionRule::Any(_) => write!(out, "**"),
            };
        }
        out
    }
}

#[derive(Debug)]
pub struct StateMachine {
    pub states: Vec<State>,
}

impl StateMachine {
    pub fn new() -> Self {
        let mut states = vec![
            State::default(), // Initial
            State::default(), // Terminal
        ];
        states[1].is_epsilon_frontier = true;
        Self {
            states,
        }
    }

    pub fn new_state(&mut self) -> StateId {
        let id = self.states.len() as StateId;
        self.states.push(State::default());
        id
    }

    pub fn connect(&mut self, from: StateId, transition: Transition) {
        let state = &mut self.states[from as usize];
        state.is_epsilon_frontier |= !transition.is_epsilon();
        state.transitions.push(transition);
    }

    pub fn transitions(&self, from: StateId) -> impl Iterator<Item = &'_ Transition> + '_ {
        self.states[from as usize].transitions.iter()
    }

    #[cfg(test)]
    pub fn between(&self, from: StateId, to: StateId) -> Vec<Transition> {
        self.states[from as usize].transitions.iter()
            .filter(|t| t.next() == to)
            .cloned()
            .collect()
    }

    pub fn initial(&self) -> StateId {
        0
    }

    pub fn terminal(&self) -> StateId {
        1
    }
}

impl Index<StateId> for StateMachine {
    type Output = State;

    fn index(&self, index: StateId) -> &Self::Output {
        &self.states[index as usize]
    }
}

/// Compiles `ast` into `sm` as a sub-machine entering at `initial` and
/// exiting at `terminal`.
pub fn compile(sm: &mut StateMachine, ast: &Ast, initial: StateId, terminal: StateId) {
    match ast {
        Ast::Empty => sm.connect(initial, Transition::Epsilon(terminal)),
        Ast::Char(c) => sm.connect(initial, Transition::Char(*c, terminal)),
        Ast::Sep => sm.connect(initial, Transition::Sep(terminal)),
        Ast::Wildcard => sm.connect(initial, Transition::Wildcard(terminal)),
        Ast::Star => {
            sm.connect(initial, Transition::Wildcard(terminal));
            sm.connect(initial, Transition::WildEpsilon(terminal));
            sm.connect(terminal, Transition::WildEpsilon(initial));
        }
        Ast::StarStar => {
            sm.connect(initial, Transition::Any(terminal));
            sm.connect(initial, Transition::WildEpsilon(terminal));
            sm.connect(terminal, Transition::WildEpsilon(initial));
        }
        Ast::Sequence(nodes) => {
            let mut initial = initial;
            for (i, node) in nodes.iter().enumerate() {
                let terminal = if i + 1 == nodes.len() {
                    terminal
                } else {
                    sm.new_state()
                };
                compile(sm, node, initial, terminal);
                initial = terminal;
            }
        }
        Ast::Alternative(branches) => {
            for branch in branches {
                compile(sm, branch, initial, terminal);
            }
        }
    }
}

pub fn from_pattern(ast: &Ast) -> StateMachine {
    let mut sm = StateMachine::new();
    compile(&mut sm, ast, 0, 1);
    sm
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::pattern::parse_ast;

    fn machine(s: &str) -> StateMachine {
        from_pattern(&parse_ast(s).unwrap())
    }

    #[test]
    fn test_compile() {
        let sm = machine("");
        assert_eq!(sm.between(0, 1), vec![Transition::Epsilon(1)]);

        let sm = machine("a");
        assert_eq!(sm.between(0, 1), vec![Transition::Char('a', 1)]);

        let sm = machine("/");
        assert_eq!(sm.between(0, 1), vec![Transition::Sep(1)]);

        let sm = machine("?");
        assert_eq!(sm.between(0, 1), vec![Transition::Wildcard(1)]);

        let sm = machine("*");
        assert_eq!(sm.between(0, 1), vec![Transition::Wildcard(1), Transition::WildEpsilon(1)]);
        assert_eq!(sm.between(1, 0), vec![Transition::WildEpsilon(0)]);

        let sm = machine("**");
        assert_eq!(sm.between(0, 1), vec![Transition::Any(1), Transition::WildEpsilon(1)]);
        assert_eq!(sm.between(1, 0), vec![Transition::WildEpsilon(0)]);

        let sm = machine("abc");
        assert_eq!(sm.between(0, 2), vec![Transition::Char('a', 2)]);
        assert_eq!(sm.between(2, 3), vec![Transition::Char('b', 3)]);
        assert_eq!(sm.between(3, 1), vec![Transition::Char('c', 1)]);

        let sm = machine("{a,b}");
        assert_eq!(
            sm.between(0, 1),
            vec![Transition::Char('a', 1), Transition::Char('b', 1)]
        );

        let sm = machine("{ab,cd}");
        assert_eq!(sm.between(0, 2), vec![Transition::Char('a', 2)]);
        assert_eq!(sm.between(2, 1), vec![Transition::Char('b', 1)]);
        assert_eq!(sm.between(0, 3), vec![Transition::Char('c', 3)]);
        assert_eq!(sm.between(3, 1), vec![Transition::Char('d', 1)]);
        assert_eq!(sm.between(0, 1), vec![]);
    }
}
