use std::fmt::Write;
use std::ops::Index;
use std::path::is_separator;

use smallvec::SmallVec;

use crate::pattern::{Ast, is_escape_char};

pub type StateId = u16;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Ord, PartialOrd)]
pub enum TransitionRule {
    // == Epsilon classes ==
    Epsilon,
    /// Epsilon edges generated by * or **. Why? When * or ** are part of the
    /// parse, they tag the automaton as being a non-literal match, *even if
    /// the rule matched no characters*. This guarantees that the pattern '.*'
    /// never matches the virtual directory '.'.
    WildEpsilon,
    // == Character classes ==
    /// Plain char
    Char(char),
    /// Path separator
    Sep,
    /// Matches anything except for Sep (used by ?, *)
    Wildcard,
    /// Matches anything including Sep (used by **)
    Any,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Ord, PartialOrd)]
pub struct Transition {
    pub next: StateId,
    pub rule: TransitionRule,
}

impl Transition {
    pub fn epsilon(next: StateId) -> Self {
        Self {
            next,
            rule: TransitionRule::Epsilon,
        }
    }

    pub fn wild_epsilon(next: StateId) -> Self {
        Self {
            next,
            rule: TransitionRule::WildEpsilon,
        }
    }

    pub fn chr(c: char, next: StateId) -> Self {
        Self {
            next,
            rule: TransitionRule::Char(c),
        }
    }

    pub fn sep(next: StateId) -> Self {
        Self {
            next,
            rule: TransitionRule::Sep,
        }
    }

    pub fn wildcard(next: StateId) -> Self {
        Self {
            next,
            rule: TransitionRule::Wildcard,
        }
    }

    pub fn any(next: StateId) -> Self {
        Self {
            next,
            rule: TransitionRule::Any,
        }
    }

    pub fn is_literal(&self) -> bool {
        match self.rule {
            TransitionRule::WildEpsilon
            | TransitionRule::Wildcard
            | TransitionRule::Any => false,
            TransitionRule::Epsilon
            | TransitionRule::Sep
            | TransitionRule::Char(_) => true,
        }
    }

    pub fn is_any_epsilon(&self) -> bool {
        matches!(self.rule, TransitionRule::Epsilon | TransitionRule::WildEpsilon)
    }

    pub fn matches(&self, token: char) -> bool {
        match self.rule {
            TransitionRule::Char(c) => token == c,
            TransitionRule::Sep => is_separator(token),
            TransitionRule::Wildcard => !is_separator(token),
            TransitionRule::Any => true,
            // Epsilon transitions never consume input
            TransitionRule::Epsilon | TransitionRule::WildEpsilon => false,
        }
    }
}

#[derive(Debug, Default)]
pub struct State {
    pub transitions: SmallVec<[Transition; 1]>,
    // TODO maybe: bitflags
    /// State has non-epsilon transitions
    pub is_epsilon_frontier: bool,
    /// State has transitions other than Sep and Epsilon (WildEpsilon counts
    /// as different from Epsilon)
    pub is_sep_frontier: bool,
    /// Has a Sep transition
    pub accepts_sep: bool,
}

impl State {
    // Debug code
    pub fn show_accepts(&self) -> String {
        let mut out = String::new();
        for t in self.transitions.iter() {
            let _ = match t.rule {
                TransitionRule::Epsilon
                | TransitionRule::WildEpsilon => write!(out, "ε"),
                TransitionRule::Char(c) if is_escape_char(c) => write!(out, "\\{c}"),
                TransitionRule::Char(c) => write!(out, "{c}"),
                TransitionRule::Sep => write!(out, "{}", std::path::MAIN_SEPARATOR),
                TransitionRule::Wildcard => write!(out, "?"),
                TransitionRule::Any => write!(out, "**"),
            };
        }
        out
    }
}

// TODO: Rename to CompiledPattern or something
#[derive(Debug)]
pub struct StateMachine {
    pub states: Vec<State>,
}

impl StateMachine {
    pub fn new() -> Self {
        let mut states = vec![
            State::default(), // Initial
            State::default(), // Terminal
        ];
        // Treating the terminal state as a frontier state very slightly
        // simplifies some logic
        states[1].is_epsilon_frontier = true;
        states[1].is_sep_frontier = true;
        Self {
            states,
        }
    }

    pub fn new_state(&mut self) -> StateId {
        let id = self.states.len() as StateId;
        self.states.push(State::default());
        id
    }

    pub fn connect(&mut self, from: StateId, transition: Transition) {
        let state = &mut self.states[from as usize];
        state.is_epsilon_frontier |= !transition.is_any_epsilon();
        state.is_sep_frontier |= !matches!(transition.rule, TransitionRule::Epsilon | TransitionRule::Sep);
        state.accepts_sep |= matches!(transition.rule, TransitionRule::Sep);
        state.transitions.push(transition);
    }

    pub fn transitions(&self, from: StateId) -> impl Iterator<Item = &'_ Transition> + '_ {
        self.states[from as usize].transitions.iter()
    }

    #[cfg(test)]
    pub fn between(&self, from: StateId, to: StateId) -> Vec<TransitionRule> {
        self.states[from as usize].transitions.iter()
            .filter(|t| t.next == to)
            .map(|t| t.rule)
            .collect()
    }

    pub fn initial(&self) -> StateId {
        0
    }

    pub fn terminal(&self) -> StateId {
        1
    }
}

impl Index<StateId> for StateMachine {
    type Output = State;

    fn index(&self, index: StateId) -> &Self::Output {
        &self.states[index as usize]
    }
}

/// Compiles `ast` into `sm` as a sub-machine entering at `initial` and
/// exiting at `terminal`.
pub fn compile(sm: &mut StateMachine, ast: &Ast, initial: StateId, terminal: StateId) {
    match ast {
        Ast::Empty => sm.connect(initial, Transition::epsilon(terminal)),
        Ast::Char(c) => sm.connect(initial, Transition::chr(*c, terminal)),
        Ast::Wildcard => sm.connect(initial, Transition::wildcard(terminal)),
        Ast::Sep => {
            let loop_state = sm.new_state();
            sm.connect(initial, Transition::sep(loop_state));
            sm.connect(loop_state, Transition::sep(loop_state));
            sm.connect(loop_state, Transition::epsilon(terminal));
        }
        Ast::Star | Ast::StarStar => {
            let loop_state = sm.new_state();
            sm.connect(initial, Transition::epsilon(loop_state));
            sm.connect(loop_state, Transition::wild_epsilon(terminal));
            match ast {
                Ast::Star => sm.connect(loop_state, Transition::wildcard(loop_state)),
                Ast::StarStar => sm.connect(loop_state, Transition::any(loop_state)),
                _ => unreachable!(),
            }
        }
        Ast::Sequence(nodes) => {
            let mut initial = initial;
            for (i, node) in nodes.iter().enumerate() {
                let terminal = if i + 1 == nodes.len() {
                    terminal
                } else {
                    sm.new_state()
                };
                compile(sm, node, initial, terminal);
                initial = terminal;
            }
        }
        Ast::Alternative(branches) => {
            for branch in branches {
                compile(sm, branch, initial, terminal);
            }
        }
    }
}

pub fn from_pattern(ast: &Ast) -> StateMachine {
    let mut sm = StateMachine::new();
    compile(&mut sm, ast, 0, 1);
    sm
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::pattern::parse_ast;

    fn machine(s: &str) -> StateMachine {
        from_pattern(&parse_ast(s).unwrap())
    }

    #[test]
    fn test_compile() {
        let sm = machine("");
        assert_eq!(sm.between(0, 1), vec![TransitionRule::Epsilon]);

        let sm = machine("a");
        assert_eq!(sm.between(0, 1), vec![TransitionRule::Char('a')]);

        let sm = machine("/");
        assert_eq!(sm.between(0, 2), vec![TransitionRule::Sep]);
        assert_eq!(sm.between(2, 2), vec![TransitionRule::Sep]);
        assert_eq!(sm.between(2, 1), vec![TransitionRule::Epsilon]);

        let sm = machine("?");
        assert_eq!(sm.between(0, 1), vec![TransitionRule::Wildcard]);

        let sm = machine("*");
        assert_eq!(sm.between(0, 2), vec![TransitionRule::Epsilon]);
        assert_eq!(sm.between(2, 2), vec![TransitionRule::Wildcard]);
        assert_eq!(sm.between(2, 1), vec![TransitionRule::WildEpsilon]);

        let sm = machine("**");
        assert_eq!(sm.between(0, 2), vec![TransitionRule::Epsilon]);
        assert_eq!(sm.between(2, 2), vec![TransitionRule::Any]);
        assert_eq!(sm.between(2, 1), vec![TransitionRule::WildEpsilon]);

        let sm = machine("abc");
        assert_eq!(sm.between(0, 2), vec![TransitionRule::Char('a')]);
        assert_eq!(sm.between(2, 3), vec![TransitionRule::Char('b')]);
        assert_eq!(sm.between(3, 1), vec![TransitionRule::Char('c')]);

        let sm = machine("{a,b}");
        assert_eq!(
            sm.between(0, 1),
            vec![TransitionRule::Char('a'), TransitionRule::Char('b')]
        );

        let sm = machine("{ab,cd}");
        assert_eq!(sm.between(0, 2), vec![TransitionRule::Char('a')]);
        assert_eq!(sm.between(2, 1), vec![TransitionRule::Char('b')]);
        assert_eq!(sm.between(0, 3), vec![TransitionRule::Char('c')]);
        assert_eq!(sm.between(3, 1), vec![TransitionRule::Char('d')]);
        assert_eq!(sm.between(0, 1), vec![]);
    }
}
