use std::fmt::Write;
use std::ops::Index;

use smallvec::SmallVec;

use crate::pattern::{Ast, is_escape_char};
use crate::test_log;

pub type StateId = u16;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Ord, PartialOrd)]
pub enum TransitionRule {
    /// Epsilon transition
    Epsilon,
    /// Non-literal epsilon (generated by * and **)
    WildEpsilon,
    /// Edge from end of current path component to beginning of next
    NextComponent,
    /// Plain char
    Char(char),
    /// Matches any character (used by ?, *, **)
    Wildcard,
}

impl TransitionRule {
    fn is_literal(self) -> bool {
        !matches!(self, Self::WildEpsilon | Self::Wildcard)
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Ord, PartialOrd)]
pub struct Transition {
    pub next: StateId,
    pub rule: TransitionRule,
}

impl Transition {
    pub fn epsilon(next: StateId) -> Self {
        Self {
            next,
            rule: TransitionRule::Epsilon,
        }
    }

    pub fn wild_epsilon(next: StateId) -> Self {
        Self {
            next,
            rule: TransitionRule::Epsilon,
        }
    }

    pub fn chr(c: char, next: StateId) -> Self {
        Self {
            next,
            rule: TransitionRule::Char(c),
        }
    }

    pub fn next_component(next: StateId) -> Self {
        Self {
            next,
            rule: TransitionRule::NextComponent,
        }
    }

    pub fn wildcard(next: StateId) -> Self {
        Self {
            next,
            rule: TransitionRule::Wildcard,
        }
    }

    pub fn is_literal(&self) -> bool {
        self.rule.is_literal()
    }

    pub fn is_wild(&self) -> bool {
        !self.rule.is_literal()
    }

    pub fn is_epsilon(&self) -> bool {
        matches!(self.rule, TransitionRule::Epsilon | TransitionRule::WildEpsilon)
    }

    pub fn matches(&self, token: char) -> bool {
        match self.rule {
            TransitionRule::Char(c) => token == c,
            TransitionRule::Wildcard => true,
            TransitionRule::Epsilon
            | TransitionRule::WildEpsilon
            | TransitionRule::NextComponent
            => false,
        }
    }
}

#[derive(Debug, Default)]
pub struct State {
    pub transitions: SmallVec<[Transition; 1]>,
}

impl State {
    // Debug code
    pub fn show_accepts(&self) -> String {
        let mut out = String::new();
        for t in self.transitions.iter() {
            let _ = match t.rule {
                TransitionRule::Epsilon
                | TransitionRule::WildEpsilon => write!(out, "ε"),
                TransitionRule::Char(c) if is_escape_char(c) => write!(out, "\\{c}"),
                TransitionRule::Char(c) => write!(out, "{c}"),
                TransitionRule::NextComponent => write!(out, "{}", std::path::MAIN_SEPARATOR),
                TransitionRule::Wildcard => write!(out, "?"),
            };
        }
        out
    }
}

// TODO: Rename to PatternGraph or something
#[derive(Debug)]
pub struct StateMachine {
    pub states: Vec<State>,
}

impl StateMachine {
    pub fn new() -> Self {
        let states = vec![
            State::default(), // Initial
            State::default(), // Terminal
        ];
        Self {
            states,
        }
    }

    pub fn new_state(&mut self) -> StateId {
        let id = self.states.len() as StateId;
        self.states.push(State::default());
        id
    }

    pub fn connect(&mut self, from: StateId, transition: Transition) {
        let state = &mut self.states[from as usize];
        state.transitions.push(transition);
    }

    pub fn transitions(&self, from: StateId) -> impl Iterator<Item = &'_ Transition> + '_ {
        self.states[from as usize].transitions.iter()
    }

    #[cfg(test)]
    pub fn between(&self, from: StateId, to: StateId) -> Vec<TransitionRule> {
        self.states[from as usize].transitions.iter()
            .filter(|t| t.next == to)
            .map(|t| t.rule)
            .collect()
    }

    pub fn initial(&self) -> StateId {
        0
    }

    pub fn terminal(&self) -> StateId {
        1
    }
}

impl Index<StateId> for StateMachine {
    type Output = State;

    fn index(&self, index: StateId) -> &Self::Output {
        &self.states[index as usize]
    }
}

/// Compiles `ast` into `sm` as a sub-machine entering at `initial` and
/// exiting at `terminal`.
pub fn compile(sm: &mut StateMachine, ast: &Ast, initial: StateId, terminal: StateId) {
    match ast {
        Ast::Empty => sm.connect(initial, Transition::epsilon(terminal)),
        Ast::Char(c) => sm.connect(initial, Transition::chr(*c, terminal)),
        Ast::Wildcard => sm.connect(initial, Transition::wildcard(terminal)),
        Ast::Sep => sm.connect(initial, Transition::next_component(terminal)),
        Ast::Star => {
            let loop_state = sm.new_state();
            sm.connect(initial, Transition::wild_epsilon(loop_state));
            sm.connect(loop_state, Transition::wild_epsilon(terminal));
            sm.connect(loop_state, Transition::wildcard(loop_state));
        }
        Ast::StarStar => {
            // Branch 1: loop, matches one or more components
            let loop_state = sm.new_state();
            sm.connect(initial, Transition::epsilon(loop_state));
            sm.connect(loop_state, Transition::wild_epsilon(terminal));
            sm.connect(loop_state, Transition::wildcard(loop_state));
            sm.connect(loop_state, Transition::next_component(loop_state));

            // Branch 2: matches zero components
            let skip_state = sm.new_state();
            sm.connect(skip_state, Transition::next_component(terminal));
        }
        Ast::Sequence(nodes) => {
            let mut initial = initial;
            for (i, node) in nodes.iter().enumerate() {
                let terminal = if i + 1 == nodes.len() {
                    terminal
                } else {
                    sm.new_state()
                };
                compile(sm, node, initial, terminal);
                initial = terminal;
            }
        }
        Ast::Alternative(branches) => {
            for branch in branches {
                compile(sm, branch, initial, terminal);
            }
        }
    }
}

pub fn from_pattern(ast: &Ast) -> StateMachine {
    let mut sm = StateMachine::new();
    compile(&mut sm, ast, 0, 1);
    test_log!("{:?}", sm.states);
    sm
}
