#[derive(Debug)]
enum TransitionRule {
    Epsilon(u16),
    WildEpsilon(u16), // Epsilon edges generated by * and **
    Char(char, u16),
    Wildcard(u16),
}

impl TransitionRule {
    fn is_wild(&self) -> bool {
        match self {
            TransitionRule::WildEpsilon(_)
            | TransitionRule::Wildcard(_) => true,
            TransitionRule::Epsilon(_)
            | TransitionRule::Char(_, _) => false,
        }
    }
}

type Transition = TransitionRule;

#[derive(Debug)]
struct State {
    transitions: Vec<Transition>,
}
